module_separator = " "
reset_color = true

palette = 'pastel_yara'

[palettes.pastel_yara]
color_white = '#ffffff'
color_a = '#9A348E'
color_b = '#DA627D'
color_c = '#FCA17D'
color_d = '#86BBD8'
color_e = '#06969A'
color_f = '#33658A'

[bookmarks]
search_depth = 100
exclude = []

# [[module]]
# type = "Symbol"
# symbol = "󱗆 "
# color = "Blue"

# [](fg:#DA627D bg:#FCA17D)\
# ${custom.jj}\
# [](fg:#FCA17D bg:#86BBD8)\
[[module]]
type = "Bookmarks"
separator = " "
# color = "white"
bg_color = "#86BBD8" # color d
color = "#1F3E5A"
behind_symbol = "+"
surround_with_quotes = false
ignore_empty_commits = "None"

# [[module]]
# type = "Commit"
# previous_message_symbol = "⇣"
# max_length = 24
# show_previous_if_empty = false
# empty_text = "(no description set)"
# surround_with_quotes = true
#
# [module.non_unique]
# color = "Black"
#
[[module]]
type = "State"
separator = " "

[module.conflict]
disabled = false
text = "(CONFLICT)"
color = "Red"
bg_color = "#FCA17D"

[module.divergent]
disabled = false
text = "(DIVERGENT)"
color = "Cyan"
bg_color = "#FCA17D"

[module.empty]
disabled = false
text = "(EMPTY)"
color = "#1F3E5A"
bg_color = "#FCA17D"

[module.immutable]
disabled = false
text = "(IMMUTABLE)"
color = "#1F3E5A"
bg_color = "#FCA17D"

[module.hidden]
disabled = false
text = "(HIDDEN)"
color = "#1F3E5A"
bg_color = "#FCA17D"

[[module]]
type = "Metrics"
template = "[{added}{removed}]"
hide_if_empty = true
color = "#1F3E5A"
bg_color = "#86BBD8" # color d

[module.added_lines]
prefix = "+"
suffix = ""
color = "#2F7D5C"
bg_color = "#86BBD8" # color d

[module.removed_lines]
prefix = "-"
suffix = ""
color = "#A23B3B"
bg_color = "#86BBD8" # color d

