[general]
import = ["~/.config/alacritty/themes/themes/solarized_light.toml"]

[font]
size = 20
normal = { family = "FantasqueSansM Nerd Font Mono", style = "regular" }
bold = { family = "FantasqueSansM Nerd Font Mono", style = "bold" }
italic = { family = "FantasqueSansM Nerd Font Mono", style = "italic" }
bold_italic = { family = "FantasqueSansM Nerd Font Mono", style = "bold_italic" }

# size = 18
# normal = { family = "CaskaydiaMono Nerd Font", style = "regular" }
# bold = { family = "CaskaydiaMono Nerd Font", style = "bold" }
# italic = { family = "CaskaydiaMono Nerd Font", style = "italic" }
# bold_italic = { family = "CaskaydiaMono Nerd Font", style = "bold_italic" }

# size = 18
# normal = { family = "FiraCode Nerd Font", style = "regular" }
# bold = { family = "FiraCode Nerd Font", style = "bold" }
# italic = { family = "FiraCode Nerd Font", style = "italic" }
# bold_italic = { family = "FiraCode Nerd Font", style = "bold_italic" }

# size = 18
# normal = { family = "iMWritingMono Nerd Font", style = "regular" }
# bold = { family = "iMWritingMono Nerd Font", style = "bold" }
# italic = { family = "iMWritingMono Nerd Font", style = "italic" }
# bold_italic = { family = "iMWritingMono Nerd Font", style = "bold_italic" }

# super broken:
# normal = { family = "OpenDyslexicAlt Nerd Font Mono", style = "regular" }
# bold = { family = "OpenDyslexic Nerd Font Mono", style = "bold" }
# italic = { family = "OpenDyslexic Nerd Font Mono", style = "italic" }
# bold_italic = { family = "OpenDyslexic Nerd Font Mono", style = "bold_italic" }
