command_timeout = 500

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[$character](bg:color_a fg:#9A348E)\
[](bg:color_b fg:color_a)\
$username\
[](bg:color_c fg:color_b)\
$directory\
[](fg:color_c bg:color_d)\
${custom.jj}\
[](fg:color_d bg:color_e)\
$c\
$golang\
$rust\
[](fg:color_e) \
"""

palette = 'pastel_yara'

[palettes.pastel_yara]
color_white = '#ffffff'
color_a = '#9A348E'
color_b = '#DA627D'
color_c = '#FCA17D'
color_d = '#86BBD8'
color_e = '#06969A'
color_f = '#33658A'

[character]
disabled = false
success_symbol = "[I](fg:color_white bg:color_a)"
vimcmd_symbol = "[N](fg:color_white bg:color_a)"
vimcmd_visual_symbol = "[V](fg:color_white bg:color_a)"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:color_b fg:#FFFFFF"
style_root = "bg:color_b fg:#FFFFFF"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "bg:color_c fg:#FFFFFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[custom.jj]
command = "prompt"
style = "bg:color_d"
format = "[ $output]($style)"
ignore_timeout = true
shell = ["starship-jj", "--ignore-working-copy", "starship"]
use_stdin = false
when = true

[custom.git_branch]
when = true
command = "jj root >/dev/null 2>&1 || starship module git_branch"
description = "Only show git_branch if we're not in a jj repo"

[git_branch]
symbol = ""
style = "bg:color_d"
format = '[[ $symbol $branch ](fg:color_white bg:color_d)]($style)'

[git_status]
style = "bg:color_d"
format = '[[($all_status$ahead_behind )](fg:color_white bg:color_d)]($style)'

[c]
symbol = " "
style = "bg:color_e"
format = '[[ $symbol( $version) ](fg:color_white bg:color_e)]($style)'

[rust]
symbol = ""
style = "bg:color_e"
format = '[[ $symbol( $version) ](fg:color_white bg:color_e)]($style)'

[python]
symbol = ""
style = "bg:color_e"
format = '[[ $symbol( $version) ](fg:color_white bg:color_e)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_e"
format = '[[  $time ](fg:color_white bg:color_e)]($style)'
